// Regenerates src/sdk/distros.ts — the proot-distro image catalog bundled with
// the extension so the Shell runtime's image dropdown works offline and needs no
// network on the deploy path. Run with `npm run build:distros`.
//
// Not part of `npm run build`: the catalog only moves when termux/proot-distro
// cuts a new v4 tag, and users can refresh it at runtime from the Settings panel
// anyway. Re-run this before a release to freshen what ships by default.
//
// The fetch/parse logic is NOT duplicated here: distroFetch.ts is transpiled with
// esbuild and imported, so the bundled catalog and the runtime refresh can never
// disagree about how a plugin file is read.

import { writeFileSync } from 'node:fs';
import { build } from 'esbuild';

const OUT = new URL('../src/sdk/distros.ts', import.meta.url);

const bundled = await build({
  entryPoints: [new URL('../src/sdk/distroFetch.ts', import.meta.url).pathname],
  bundle: true,
  format: 'esm',
  platform: 'node',
  write: false,
});
const mod = await import(
  `data:text/javascript;base64,${Buffer.from(bundled.outputFiles[0].text).toString('base64')}`
);

const catalog = await mod.fetchDistroCatalog();

const s = (v) => JSON.stringify(v);

const groups = catalog.groups
  .map((g) => {
    const distros = g.distros
      .map((d) => {
        const comment = d.comment ? `\n        comment: ${s(d.comment)},` : '';
        return `      {
        id: ${s(d.id)},
        name: ${s(d.name)},${comment}
        url: ${s(d.url)},
        sha256: ${s(d.sha256)},
      },`;
      })
      .join('\n');
    return `  {
    label: ${s(g.label)},
    tag: ${s(g.tag)},
    host: ${s(g.host)},
    distros: [
${distros}
    ],
  },`;
  })
  .join('\n');

writeFileSync(
  OUT,
  `// GENERATED by \`npm run build:distros\` — do not edit by hand.
//
// aarch64 rootfs images read from termux/proot-distro's distro-plugins/*.sh.
// See src/sdk/distroFetch.ts for why the catalog is read from v4 tags, pinned
// per distro rather than per release, and split into two host groups.

import type { DistroCatalog } from '../studio/types';

export const BUNDLED_DISTROS: DistroCatalog = {
  fetchedAt: ${s(catalog.fetchedAt)},
  groups: [
${groups}
  ],
};
`,
);

const summary = catalog.groups.map((g) => `${g.distros.length} from ${g.tag} (${g.host})`).join(', ');
console.log(`Wrote src/sdk/distros.ts: ${summary}`);
